In [2]:
import pandas as pd
df1 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Bio-Diesel_PassengerVehicle_Stats.csv")
df1
df2 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Compressed Natural Gas_PassengerVehicle_Stats.csv")
df2
df3 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Diesel_PassengerVehicle_Stats.csv")
df3
df4 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Electric_PassengerVehicle_Stats.csv")
df4
df5 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Flex Fuel_PassengerVehicle_Stats.csv")
df5
df6 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Gasoline_PassengerVehicle_Stats.csv")
df6
df7 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Horse_PassengerVehicle_Stats.csv")
df7
df8 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Hybrid_PassengerVehicle_Stats.csv")
df8
df9 = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Python g project\CASE3\PassengerVehicle_Stats\Pedal_PassengerVehicle_Stats.csv")
df9

,Unnamed: 0,Public Vehicle Number,Status,Vehicle Make,Vehicle Model,Vehicle Model Year,Vehicle Color,Vehicle Fuel Source,Wheelchair Accessible,Company Name,Address,City,State,ZIP Code,Taxi Affiliation,Taxi Medallion License Management,Record ID
0,61,77,VIOLATION,MAINSTREET,CLASSIC,0.0,RED/BLACK,Pedal,N,EMPIRE PEDICAB LLC,318 W. ADAMS ST.,CHICAGO,IL,60606.0,NaN,NaN,77Pedicab
1,103,131,ACTIVE,MANMADE,WAGON,2011.0,BLACK,Pedal,N,TROTTERS LLC,4955 N. MANGO AVE.,CHICAGO,IL,60630.0,NaN,NaN,131Pedicab
2,168,186,ACTIVE,MANMADE,BROADWAY,2014.0,BLACK,Pedal,N,MBL PEDICAB LLC,8708 W. BERWYN AVE.,CHICAGO,IL,60656.0,NaN,NaN,186Pedicab
3,227,69,VIOLATION,MAINSTREET,CLASSIC,0.0,RED/BLACK,Pedal,N,EMPIRE PEDICAB LLC,318 W. ADAMS ST.,CHICAGO,IL,60606.0,NaN,NaN,69Pedicab
4,261,142,ACTIVE,VIP,VIP,2018.0,BLUE/WHITE,Pedal,N,PEDICAB RIDE GUYS LLC,1919 S. MICHIGAN AVE. AVE.,CHICAGO,IL,60616.0,NaN,NaN,142Pedicab
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,16143,42,ACTIVE,PRECISION,6 SEATER,2020.0,FUSCIA,Pedal,N,JBL PEDICAB MANAGEMENT LLC,1627 N. TRIPP AVE.,CHICAGO,IL,60639.0,NaN,NaN,42Pedicab
211,16151,52,ACTIVE,SCHWINN,NONE,2014.0,GREEN,Pedal,N,BM PEDICAB INC.,4450 N. KEDZIE AVE.,CHICAGO,IL,60625.0,NaN,NaN,52Pedicab
212,16216,70,VIOLATION,MAINSTREET,CLASSIC,0.0,RED/BLACK,Pedal,N,EMPIRE PEDICAB LLC,318 W. ADAMS ST.,CHICAGO,IL,60606.0,NaN,NaN,70Pedicab
213,16229,57,VIOLATION,MAINSTREET,BOARDWALK,2011.0,RED,Pedal,N,CARGILL C KELLY II,2428 W. 24TH PL.,CHICAGO,IL,60608.0,NaN,NaN,57Pedicab
214,16281,117,ACTIVE,SCHWINN,NONE,2014.0,GREEN,Pedal,N,BM PEDICAB INC.,4450 N. KEDZIE AVE.,CHICAGO,IL,60625.0,NaN,NaN,117Pedicab

In [3]:
vehicles_df = pd.concat([df1, df2, df3, df4, df6,df7, df8, df9], join = 'inner' )
vehicles_df

,Unnamed: 0,Public Vehicle Number,Status,Vehicle Make,Vehicle Model,Vehicle Model Year,Vehicle Color,Vehicle Fuel Source,Wheelchair Accessible,Company Name,Address,City,State,ZIP Code,Taxi Affiliation,Taxi Medallion License Management,Record ID
0,1286,12009,RESERVED,CHEVROLET,EXPRESS,2014.0,BLACK,Bio-Diesel,N,CHICAGO PRIVATE TOURS LLC,4567 S. OAKENWALD AVE.,CHICAGO,IL,60653.0,NaN,NaN,12009Charter Sightseeing
1,2095,12248,INACTIVE,MERCEDES,SPRINTER,2010.0,SILVER,Bio-Diesel,N,O'HARE-MIDWAY LIMOUSINE SERVICE INC # 2,4610 N. CLARK ST.,CHICAGO,IL,60640.0,NaN,NaN,12248Charter Sightseeing
2,7950,13527,INACTIVE,VAN HOOL,TD925,2008.0,RED,Bio-Diesel,N,"TRT TRANSPORTATION, INC.",4400 S. RACINE AVE.,CHICAGO,IL,60609.0,NaN,NaN,13527Charter Sightseeing
3,8700,12248,INACTIVE,MERCEDES,SPRINTER,2010.0,SILVER,Bio-Diesel,N,O'HARE-MIDWAY LIMOUSINE SERVICE INC # 2,4610 N. CLARK ST.,CHICAGO,IL,60640.0,NaN,NaN,12248Charter Sightseeing
4,9359,13528,INACTIVE,VAN HOOL,TD925,2008.0,RED,Bio-Diesel,N,"TRT TRANSPORTATION, INC.",4400 S. RACINE AVE.,CHICAGO,IL,60609.0,NaN,NaN,13528Charter Sightseeing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,16143,42,ACTIVE,PRECISION,6 SEATER,2020.0,FUSCIA,Pedal,N,JBL PEDICAB MANAGEMENT LLC,1627 N. TRIPP AVE.,CHICAGO,IL,60639.0,NaN,NaN,42Pedicab
211,16151,52,ACTIVE,SCHWINN,NONE,2014.0,GREEN,Pedal,N,BM PEDICAB INC.,4450 N. KEDZIE AVE.,CHICAGO,IL,60625.0,NaN,NaN,52Pedicab
212,16216,70,VIOLATION,MAINSTREET,CLASSIC,0.0,RED/BLACK,Pedal,N,EMPIRE PEDICAB LLC,318 W. ADAMS ST.,CHICAGO,IL,60606.0,NaN,NaN,70Pedicab
213,16229,57,VIOLATION,MAINSTREET,BOARDWALK,2011.0,RED,Pedal,N,CARGILL C KELLY II,2428 W. 24TH PL.,CHICAGO,IL,60608.0,NaN,NaN,57Pedicab
214,16281,117,ACTIVE,SCHWINN,NONE,2014.0,GREEN,Pedal,N,BM PEDICAB INC.,4450 N. KEDZIE AVE.,CHICAGO,IL,60625.0,NaN,NaN,117Pedicab